import { MIN_HISTORY_PER_TEAM, RECOMMENDED_HISTORY_PER_TEAM, type MatchPackage } from "@/lib/validation/match-package";

// ============================================================================
// Contenido de la pantalla "Agregar partido": el prompt copiable para pedirle
// a otra IA (Claude, ChatGPT, etc.) que investigue un partido y devuelva el
// JSON, más un ejemplo válido que ilustra la estructura exacta.
// ============================================================================

export const MATCH_PACKAGE_EXAMPLE: MatchPackage = {
  id: "equipo-local-ejemplo-vs-equipo-visitante-ejemplo-2026-08-04",
  researchedAt: "2026-08-04T10:00:00.000Z",
  sourceUrls: ["https://www.fotmob.com/", "https://www.rsssf.org/"],
  competitions: [
    {
      id: "liga-ejemplo",
      name: "Liga de Ejemplo",
      shortName: "Liga Ejemplo",
      country: "País Ejemplo",
      tier: 1,
      season: "2026",
      color: "#16A34A",
      totalTeams: 20,
    },
  ],
  teams: [
    {
      id: "equipo-local-ejemplo",
      name: "Equipo Local FC (ejemplo)",
      shortName: "Local FC",
      code: "LOC",
      country: "País Ejemplo",
      competitionId: "liga-ejemplo",
      stadium: "Estadio Ejemplo",
      founded: 1900,
      primaryColor: "#16A34A",
      secondaryColor: "#FFFFFF",
      position: 1,
      played: 20,
      won: 12,
      drawn: 5,
      lost: 3,
      goalsFor: 35,
      goalsAgainst: 18,
      points: 41,
      form: ["W", "W", "D", "W", "L"],
      avgGoalsFor: 1.75,
      avgGoalsAgainst: 0.9,
      avgCorners: 5.6,
    },
    {
      id: "equipo-visitante-ejemplo",
      name: "Equipo Visitante FC (ejemplo)",
      shortName: "Visitante FC",
      code: "VIS",
      country: "País Ejemplo",
      competitionId: "liga-ejemplo",
      stadium: "Estadio Visitante",
      founded: 1900,
      primaryColor: "#111827",
      secondaryColor: "#FFFFFF",
      position: 5,
      played: 20,
      won: 10,
      drawn: 6,
      lost: 4,
      goalsFor: 30,
      goalsAgainst: 22,
      points: 36,
      form: ["D", "W", "W", "L", "D"],
      avgGoalsFor: 1.5,
      avgGoalsAgainst: 1.1,
      avgCorners: 4.8,
    },
  ],
  match: {
    id: "equipo-local-ejemplo-vs-equipo-visitante-ejemplo-1",
    competitionId: "liga-ejemplo",
    competitionType: "league",
    season: "2026",
    matchday: 10,
    date: "2026-08-04",
    time: "20:00",
    stadium: "Estadio Ejemplo",
    homeTeamId: "equipo-local-ejemplo",
    awayTeamId: "equipo-visitante-ejemplo",
    status: "scheduled",
  },
  histories: {
    "equipo-local-ejemplo": [
      {
        matchId: "equipo-local-ejemplo-h1",
        date: "2026-07-28",
        opponentId: "rival-anterior-1",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        cornersFor: 6,
        cornersAgainst: 3,
        shotsFor: 14,
        shotsAgainst: 8,
        shotsOnTargetFor: 6,
        shotsOnTargetAgainst: 2,
        possession: 56,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h2",
        date: "2026-07-21",
        opponentId: "rival-anterior-2",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        cornersFor: 5,
        cornersAgainst: 4,
        shotsFor: 10,
        shotsAgainst: 9,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 3,
        possession: 52,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h3",
        date: "2026-07-14",
        opponentId: "rival-anterior-3",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 3,
        goalsAgainst: 1,
        cornersFor: 7,
        cornersAgainst: 2,
        shotsFor: 16,
        shotsAgainst: 7,
        shotsOnTargetFor: 8,
        shotsOnTargetAgainst: 3,
        possession: 60,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h4",
        date: "2026-07-07",
        opponentId: "rival-anterior-4",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 2,
        cornersFor: 3,
        cornersAgainst: 6,
        shotsFor: 8,
        shotsAgainst: 13,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 6,
        possession: 44,
        yellowCards: 3,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h5",
        date: "2026-06-30",
        opponentId: "rival-anterior-9",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 1,
        cornersFor: 6,
        cornersAgainst: 4,
        shotsFor: 13,
        shotsAgainst: 9,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 3,
        possession: 54,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h6",
        date: "2026-06-23",
        opponentId: "rival-anterior-10",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        cornersFor: 4,
        cornersAgainst: 5,
        shotsFor: 9,
        shotsAgainst: 10,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 4,
        possession: 49,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h7",
        date: "2026-06-16",
        opponentId: "rival-anterior-11",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 4,
        goalsAgainst: 2,
        cornersFor: 8,
        cornersAgainst: 5,
        shotsFor: 18,
        shotsAgainst: 11,
        shotsOnTargetFor: 9,
        shotsOnTargetAgainst: 4,
        possession: 58,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h8",
        date: "2026-06-09",
        opponentId: "rival-anterior-12",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 1,
        goalsAgainst: 3,
        cornersFor: 3,
        cornersAgainst: 7,
        shotsFor: 7,
        shotsAgainst: 15,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 7,
        possession: 41,
        yellowCards: 3,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h9",
        date: "2026-06-02",
        opponentId: "rival-anterior-13",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        cornersFor: 7,
        cornersAgainst: 3,
        shotsFor: 15,
        shotsAgainst: 8,
        shotsOnTargetFor: 7,
        shotsOnTargetAgainst: 2,
        possession: 57,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h10",
        date: "2026-05-26",
        opponentId: "rival-anterior-14",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        cornersFor: 5,
        cornersAgainst: 5,
        shotsFor: 10,
        shotsAgainst: 10,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 4,
        possession: 50,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
    ],
    "equipo-visitante-ejemplo": [
      {
        matchId: "equipo-visitante-ejemplo-h1",
        date: "2026-07-29",
        opponentId: "rival-anterior-5",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        cornersFor: 4,
        cornersAgainst: 5,
        shotsFor: 10,
        shotsAgainst: 11,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 4,
        possession: 48,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h2",
        date: "2026-07-22",
        opponentId: "rival-anterior-6",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        cornersFor: 6,
        cornersAgainst: 2,
        shotsFor: 12,
        shotsAgainst: 6,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 1,
        possession: 55,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h3",
        date: "2026-07-15",
        opponentId: "rival-anterior-7",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 1,
        cornersFor: 3,
        cornersAgainst: 5,
        shotsFor: 7,
        shotsAgainst: 12,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 5,
        possession: 41,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h4",
        date: "2026-07-08",
        opponentId: "rival-anterior-8",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 2,
        goalsAgainst: 2,
        cornersFor: 5,
        cornersAgainst: 5,
        shotsFor: 9,
        shotsAgainst: 9,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 4,
        possession: 50,
        yellowCards: 3,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h5",
        date: "2026-07-01",
        opponentId: "rival-anterior-9",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 3,
        goalsAgainst: 1,
        cornersFor: 7,
        cornersAgainst: 3,
        shotsFor: 14,
        shotsAgainst: 8,
        shotsOnTargetFor: 6,
        shotsOnTargetAgainst: 3,
        possession: 53,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h6",
        date: "2026-06-24",
        opponentId: "rival-anterior-10",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 2,
        cornersFor: 3,
        cornersAgainst: 6,
        shotsFor: 6,
        shotsAgainst: 13,
        shotsOnTargetFor: 1,
        shotsOnTargetAgainst: 6,
        possession: 39,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h7",
        date: "2026-06-17",
        opponentId: "rival-anterior-11",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        cornersFor: 5,
        cornersAgainst: 4,
        shotsFor: 9,
        shotsAgainst: 9,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 3,
        possession: 47,
        yellowCards: 3,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h8",
        date: "2026-06-10",
        opponentId: "rival-anterior-12",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        cornersFor: 6,
        cornersAgainst: 2,
        shotsFor: 11,
        shotsAgainst: 5,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 1,
        possession: 56,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h9",
        date: "2026-06-03",
        opponentId: "rival-anterior-13",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 2,
        goalsAgainst: 2,
        cornersFor: 4,
        cornersAgainst: 4,
        shotsFor: 8,
        shotsAgainst: 8,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 3,
        possession: 50,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h10",
        date: "2026-05-27",
        opponentId: "rival-anterior-14",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 1,
        cornersFor: 3,
        cornersAgainst: 5,
        shotsFor: 6,
        shotsAgainst: 11,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 5,
        possession: 43,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
    ],
  },
  dataQuality: {
    resultData: "verified",
    providedAdvancedStats: "provided",
    newAdvancedStats: "estimated",
    warning: "Los córners y remates de los partidos marcados como 'estimated' no se publican en la fuente y se estimaron a partir del marcador.",
  },
  historyMeta: {
    matchesPerTeam: 10,
    newMatchesPerTeam: 10,
    sortOrder: "date_desc",
    verifiedFieldsForNewMatches: ["date", "opponentId", "competitionId", "venue", "result", "goalsFor", "goalsAgainst"],
    estimatedFieldsForNewMatches: [
      "cornersFor",
      "cornersAgainst",
      "shotsFor",
      "shotsAgainst",
      "shotsOnTargetFor",
      "shotsOnTargetAgainst",
      "possession",
      "yellowCards",
      "redCards",
    ],
  },
};

export const MATCH_PACKAGE_EXAMPLE_JSON = JSON.stringify({ version: 1, packages: [MATCH_PACKAGE_EXAMPLE] }, null, 2);

export const MATCH_PACKAGE_PROMPT = `Actúa como un investigador deportivo riguroso, no como un generador de datos plausibles. Necesito que investigues un partido de fútbol REAL (te diré cuál, o pregúntame si no te lo especifiqué) usando fuentes reales que hayas consultado de verdad, y me devuelvas exclusivamente un JSON con esta estructura exacta:

${MATCH_PACKAGE_EXAMPLE_JSON}

REGLA CERO, POR ENCIMA DE TODAS LAS DEMÁS: TERMINANTEMENTE PROHIBIDO INVENTAR DATOS.
Cada equipo, partido, fecha, resultado, rival, competición y fuente que pongas en el JSON tiene que corresponder a algo real que efectivamente encontraste al investigar — no a algo "razonable", "típico" o "que probablemente pasó". Si en algún momento no encontrás el dato real y no podés dejar de completar el campo (porque el esquema lo exige), tenés exactamente dos salidas válidas, nunca una tercera inventada:
   (a) Estimarlo de forma explícita y declarada como tal (ver regla 4), siempre partiendo de algo real (el marcador del partido, el promedio de la liga, el nivel de los equipos) — nunca un número que te "suene bien".
   (b) Preguntarme a mí en vez de completar el campo (ver regla 15).
Inventar resultados, marcadores, fechas, rivales, nombres de equipos, colores, estadios, o URLs de fuentes que no visitaste realmente es un fallo grave, no un detalle menor — arruina el propósito completo de este sistema, que es analizar datos reales, no ficción con apariencia de dato.

REGLAS QUE DEBES SEGUIR SIN EXCEPCIÓN:

1. Responde ÚNICAMENTE con el JSON. Nada de Markdown, nada de bloques de código (sin \`\`\`), nada de explicaciones antes o después, nada de comentarios dentro del JSON.
2. Respeta EXACTAMENTE la estructura del ejemplo: mismos nombres de campo, mismos tipos de dato, mismo anidamiento. No agregues campos que no estén en el ejemplo ni elimines campos obligatorios.
3. Usa ids únicos y en kebab-case (minúsculas, con guiones, sin espacios ni acentos) para "packages[].id", equipos, competiciones y "match.id". "histories" debe tener exactamente dos claves, una por cada id de "teams".
4. No inventes datos que se presenten como verificados. Resultados, marcadores, fechas, rivales, nombres, posiciones en tabla y URLs de fuentes deben salir de algo que realmente consultaste — jamás de una suposición. Todo lo que no puedas confirmar en una fuente real debe:
   - Marcarse con "statsStatus": "estimated" (o "resultStatus": "estimated" si el resultado mismo no está confirmado) en cada registro de historial afectado.
   - Explicarse en "dataQuality.warning", dejando claro qué parte es real y qué parte es estimación.
   Si terminás el JSON y no podrías señalar, para cada dato marcado como "verified", en qué fuente concreta de "sourceUrls" lo confirmaste, ese dato está mal marcado — bajalo a "estimated" o volvé a investigar.
5. Incluye EXACTAMENTE ${RECOMMENDED_HISTORY_PER_TEAM} partidos históricos reales por equipo en "histories" (nunca menos de ${MIN_HISTORY_PER_TEAM}, pero el estándar exigido es ${RECOMMENDED_HISTORY_PER_TEAM} para cada uno de los dos equipos, sin excepción). Cada registro con su "matchId" único. Si un equipo no tiene ${RECOMMENDED_HISTORY_PER_TEAM} partidos disputados todavía (equipo nuevo, temporada recién iniciada), incluye todos los que existan realmente, nunca menos de ${MIN_HISTORY_PER_TEAM}, y acláralo en "dataQuality.warning" — jamás inventes partidos para completar el número.
6. Ordena cada lista de historial de más reciente a más antiguo (por "date", descendente) — igual que en el ejemplo.
7. Incluye "sourceUrls" con las fuentes REALES que efectivamente consultaste para armar este JSON (mínimo una, URLs completas). No pongas una URL "típica" de un sitio de estadísticas si no la visitaste de verdad en esta investigación — cada fuente listada debe respaldar al menos un dato concreto que aparece en el paquete.
8. Usa fechas en formato YYYY-MM-DD, horas en HH:mm (24 horas) y "researchedAt" en formato ISO 8601 completo (YYYY-MM-DDTHH:mm:ss.000Z).
9. Usa colores hexadecimales de 6 dígitos (con #) para los campos de color.
10. "competitionType" debe ser uno de: league, cup, continental, friendly. "match.status" debe ser uno de: scheduled, live, finished, postponed.
11. "tier" y "totalTeams" de CADA competición en "competitions" deben ser números enteros mayores a 0, SIEMPRE — incluso para competiciones que no son una liga con tabla, como amistosos de pretemporada ("friendly"/"Club Friendlies"). En ese caso usa "tier": 1 y "totalTeams": 1 (nunca 0). Un valor de 0 en cualquiera de los dos hace que el JSON sea inválido.
12. Los campos "dataQuality.resultData", "dataQuality.providedAdvancedStats", "dataQuality.newAdvancedStats", y "resultStatus"/"statsStatus" de CADA registro de historial, SOLO pueden valer exactamente "verified", "provided" o "estimated" — nunca "none", "n/a", "unknown", "unavailable", "no_data", "not_available", "missing", ni ninguna otra palabra que se te ocurra para decir "no lo sé". Aunque te parezca más honesto inventar un cuarto estado, NO EXISTE: el validador solo acepta esos tres valores exactos y cualquier otro hace que el JSON entero sea rechazado. Si el dato no está disponible en ninguna fuente, usa "estimated" (ver regla siguiente) y explica la limitación en texto dentro de "dataQuality.warning".
13. Nunca completes un campo numérico que no encontraste con "0" repetido en todos los partidos como si fuera un marcador de "sin datos" — un 0 en "cornersFor", "shotsFor", "shotsOnTargetFor", "possession", etc. se interpreta como el valor real (cero córners, cero remates), y el sistema va a mostrarlo como un patrón real y falso (ej. "nunca superó los 0.5 córners"). Si de verdad no encontraste el dato exacto, estimalo de forma razonable a partir de: el promedio típico de esa liga/categoría, el marcador del partido, o el nivel de los equipos — y marca ese registro como "estimated", explicando en "dataQuality.warning" que son estimaciones y no cifras oficiales. Rellenar todo con 0 nunca es una estimación válida.
14. "match.time" y todas las horas que uses deben estar en la ZONA HORARIA LOCAL DEL ESTADIO donde se juega ("match.stadium"), no en tu propia zona horaria ni en la del usuario. Si detectas una diferencia horaria relevante entre fuentes, acláralo en texto dentro de "dataQuality.warning", pero nunca escribas la hora convertida a otro huso en el campo "time".
15. Antes de generar el JSON, si te falta información imprescindible (qué partido, en qué fecha, qué liga), PREGÚNTAME — no completes huecos con datos inventados.
16. Verifica tú mismo, antes de responder, que el JSON sea sintácticamente válido y que pueda ser procesado por un validador estricto (sin comas colgantes, sin comentarios, todas las comillas dobles, sin campos con valores fuera de los permitidos, y sin estadísticas numéricas en 0 repetidas en todos los partidos como relleno).
17. "yellowCards" y "redCards" son SIEMPRE las tarjetas del equipo investigado en ese registro, nunca las del rival — no existe un campo "para el rival" obligatorio. Si la fuente que consultaste también publica las tarjetas del RIVAL en ese mismo partido histórico, podés (opcionalmente) agregar "yellowCardsAgainst" y/o "redCardsAgainst" con ese dato real — nunca inventados ni estimados, solo si los confirmaste. Si no los tenés, simplemente omití esos dos campos (son opcionales, el JSON es válido sin ellos).

CHEQUEO FINAL OBLIGATORIO ANTES DE RESPONDER (hazlo en silencio, no lo escribas en la respuesta):
Repasa cada dato del JSON que estás por enviar y preguntate, uno por uno: "¿esto lo encontré de verdad en una fuente real, o lo estoy completando porque me falta el dato?". Si la respuesta es la segunda, ese campo tiene que estar marcado "estimated" (o preguntado antes de responder, nunca completado en silencio) — no hay una tercera opción de "lo dejo como si fuera real total nadie se va a dar cuenta". Este chequeo aplica también a "sourceUrls": no la incluyas si no la usaste de verdad.

Cuando tengas toda la información, responde solo con el JSON.`;
