import { MIN_HISTORY_PER_TEAM, RECOMMENDED_HISTORY_PER_TEAM, type MatchPackage } from "@/lib/validation/match-package";

// El prompt copiable usa una muestra mas corta que el flujo automatico de
// API-Football. El esquema acepta esta cantidad (minimo: 4).
const STRICT_PROMPT_HISTORY_PER_TEAM = 5;

/**
 * Prompt visible en "Agregar partido". Se mantiene separado del ejemplo para
 * impedir que una IA trate los valores ilustrativos como datos utilizables.
 */
export function getStrictMatchPackagePrompt(): string {
  return `Eres un investigador deportivo. Tu unica tarea es entregar un paquete JSON con datos 100% REALES, COMPLETOS y COMPROBABLES del partido que te indique el usuario.

REGLA ABSOLUTA
No inventes, no estimes, no redondees, no rellenes huecos, no uses promedios como si fueran datos de un partido, no deduzcas estadisticas desde el marcador final y no reutilices datos de otro encuentro. Cada valor debe haber sido publicado por una fuente real y poder verificarse por separado.

ANTES DE RESPONDER
1. Investiga el partido, ambos equipos, la competicion y los ultimos ${STRICT_PROMPT_HISTORY_PER_TEAM} encuentros reales de CADA equipo.
2. Abre y comprueba fuentes reales. Para cada partido historico verifica marcador, goles de primera y segunda parte, corners, remates, remates al arco, posesion y tarjetas de ambos equipos.
3. Comprueba que las sumas son correctas: goles de primera parte + segunda parte = goles finales, para ambos equipos.
4. No uses un dato si no puedes encontrar la fuente concreta que lo publica. Una pagina de resumen, una prediccion, una cuota, una IA o un marcador sin desglose no sirven como prueba para completar estadisticas.

DATOS OBLIGATORIOS, TODOS REALES
- Completa TODOS los campos de competiciones, equipos y match, incluidos estadio, fundacion, clasificacion, tabla, forma, medias, fecha, hora, jornada y estado real del partido.
- Incluye exactamente dos equipos y exactamente ${STRICT_PROMPT_HISTORY_PER_TEAM} registros historicos completos por cada uno, ordenados del mas reciente al mas antiguo.
- En CADA registro de histories completa sin excepcion: matchId, date, opponentId, competitionId, competitionType, venue, result, goalsFor, goalsAgainst, goalsForFirstHalf, goalsForSecondHalf, goalsAgainstFirstHalf, goalsAgainstSecondHalf, cornersFor, cornersAgainst, shotsFor, shotsAgainst, shotsOnTargetFor, shotsOnTargetAgainst, possession, yellowCards, redCards, yellowCardsAgainst, redCardsAgainst, resultStatus, statsStatus y note.
- Cada note debe incluir la URL completa de la pagina concreta que respalda ese partido. sourceUrls debe incluir todas las URLs reales consultadas; no inventes ni reutilices URLs que no hayas abierto.
- Incluye dataQuality e historyMeta completos. Usa resultStatus: "verified", statsStatus: "provided", dataQuality.resultData: "verified", dataQuality.providedAdvancedStats: "provided", dataQuality.newAdvancedStats: "provided". historyMeta.estimatedFieldsForNewMatches debe ser [].
- El valor "estimated" esta prohibido en cualquier campo del JSON final. Tambien estan prohibidos null, "N/A", "desconocido", 0 de relleno, guiones, textos de marcador de posicion y valores supuestos.

CUANDO FALTE CUALQUIER DATO
Si no logras verificar el 100% de los campos obligatorios de los ${STRICT_PROMPT_HISTORY_PER_TEAM} partidos de ambos equipos, NO generes JSON, NO generes JSON parcial y NO completes nada por tu cuenta. Responde solamente una linea con este formato:
NO PUEDO GENERAR EL JSON: falta verificar [campo(s)] de [partido(s)]. Comparte una fuente que contenga esos datos reales.

PLANTILLA DE ESTRUCTURA
El siguiente contenido sirve UNICAMENTE para conocer las claves, los tipos y el orden del JSON. No es una fuente, no son datos reales del partido solicitado y no se puede copiar ningun valor. Sustituye absolutamente todos sus IDs, fechas, equipos, competiciones, URLs, cantidades y textos por datos reales verificados.

${MATCH_PACKAGE_EXAMPLE_JSON}

CONTROL FINAL OBLIGATORIO
Antes de responder, revisa uno por uno estos puntos: todos los valores son reales; cada valor tiene una fuente real consultada; hay ${STRICT_PROMPT_HISTORY_PER_TEAM} historiales completos por equipo; no hay estimaciones ni campos omitidos; los identificadores coinciden entre equipos, partido e historiales; las URLs son validas; y el JSON cumple exactamente la plantilla.

SALIDA
Solo si todos los controles anteriores se cumplen, crea un ARCHIVO descargable con extension .json y adjuntalo a tu respuesta. El nombre debe ser el valor exacto de "id" mas ".json"; por ejemplo: equipo-local-vs-equipo-visitante-2026-08-04.json.

El contenido del archivo debe ser exclusivamente un unico objeto JSON valido, sin Markdown, sin explicaciones, sin comentarios y sin texto antes o despues. No pegues el JSON como texto en el chat: entrega el archivo .json para que el usuario lo descargue y lo suba al sistema.

Si tu entorno no tiene capacidad real de crear y adjuntar archivos, NO pegues el JSON en texto. Responde solamente: NO PUEDO CREAR EL ARCHIVO .json: usa una IA con capacidad para adjuntar archivos.

De lo contrario, si falta algun dato, usa exclusivamente el mensaje de bloqueo de datos indicado arriba.`;
}

// ============================================================================
// Contenido de la pantalla "Agregar partido": el prompt copiable para pedirle
// a otra IA (Claude, ChatGPT, etc.) que investigue un partido y devuelva el
// JSON, más un ejemplo válido que ilustra la estructura exacta.
// ============================================================================

export const MATCH_PACKAGE_EXAMPLE: MatchPackage = {
  id: "equipo-local-ejemplo-vs-equipo-visitante-ejemplo-2026-08-04",
  researchedAt: "2026-08-04T10:00:00.000Z",
  sourceUrls: ["https://www.fotmob.com/", "https://www.rsssf.org/"],
  competitions: [
    {
      id: "liga-ejemplo",
      name: "Liga de Ejemplo",
      shortName: "Liga Ejemplo",
      country: "País Ejemplo",
      tier: 1,
      season: "2026",
      color: "#16A34A",
      totalTeams: 20,
    },
  ],
  teams: [
    {
      id: "equipo-local-ejemplo",
      name: "Equipo Local FC (ejemplo)",
      shortName: "Local FC",
      code: "LOC",
      country: "País Ejemplo",
      competitionId: "liga-ejemplo",
      stadium: "Estadio Ejemplo",
      founded: 1900,
      primaryColor: "#16A34A",
      secondaryColor: "#FFFFFF",
      position: 1,
      played: 20,
      won: 12,
      drawn: 5,
      lost: 3,
      goalsFor: 35,
      goalsAgainst: 18,
      points: 41,
      form: ["W", "W", "D", "W", "L"],
      avgGoalsFor: 1.75,
      avgGoalsAgainst: 0.9,
      avgCorners: 5.6,
    },
    {
      id: "equipo-visitante-ejemplo",
      name: "Equipo Visitante FC (ejemplo)",
      shortName: "Visitante FC",
      code: "VIS",
      country: "País Ejemplo",
      competitionId: "liga-ejemplo",
      stadium: "Estadio Visitante",
      founded: 1900,
      primaryColor: "#111827",
      secondaryColor: "#FFFFFF",
      position: 5,
      played: 20,
      won: 10,
      drawn: 6,
      lost: 4,
      goalsFor: 30,
      goalsAgainst: 22,
      points: 36,
      form: ["D", "W", "W", "L", "D"],
      avgGoalsFor: 1.5,
      avgGoalsAgainst: 1.1,
      avgCorners: 4.8,
    },
  ],
  match: {
    id: "equipo-local-ejemplo-vs-equipo-visitante-ejemplo-1",
    competitionId: "liga-ejemplo",
    competitionType: "league",
    season: "2026",
    matchday: 10,
    date: "2026-08-04",
    time: "20:00",
    stadium: "Estadio Ejemplo",
    homeTeamId: "equipo-local-ejemplo",
    awayTeamId: "equipo-visitante-ejemplo",
    status: "scheduled",
  },
  histories: {
    "equipo-local-ejemplo": [
      {
        matchId: "equipo-local-ejemplo-h1",
        date: "2026-07-28",
        opponentId: "rival-anterior-1",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 0,
        cornersFor: 6,
        cornersAgainst: 3,
        shotsFor: 14,
        shotsAgainst: 8,
        shotsOnTargetFor: 6,
        shotsOnTargetAgainst: 2,
        possession: 56,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h2",
        date: "2026-07-21",
        opponentId: "rival-anterior-2",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 5,
        cornersAgainst: 4,
        shotsFor: 10,
        shotsAgainst: 9,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 3,
        possession: 52,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h3",
        date: "2026-07-14",
        opponentId: "rival-anterior-3",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 3,
        goalsAgainst: 1,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 2,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 7,
        cornersAgainst: 2,
        shotsFor: 16,
        shotsAgainst: 7,
        shotsOnTargetFor: 8,
        shotsOnTargetAgainst: 3,
        possession: 60,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h4",
        date: "2026-07-07",
        opponentId: "rival-anterior-4",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 2,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 0,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 1,
        cornersFor: 3,
        cornersAgainst: 6,
        shotsFor: 8,
        shotsAgainst: 13,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 6,
        possession: 44,
        yellowCards: 3,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h5",
        date: "2026-06-30",
        opponentId: "rival-anterior-9",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 1,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 6,
        cornersAgainst: 4,
        shotsFor: 13,
        shotsAgainst: 9,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 3,
        possession: 54,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 3,
        redCardsAgainst: 1,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h6",
        date: "2026-06-23",
        opponentId: "rival-anterior-10",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        // Ejemplo de registro donde SÍ se investigó a fondo pero la fuente
        // consultada no publicaba el marcador al descanso ni las tarjetas
        // del rival para este partido puntual: se omiten (nunca se estiman,
        // porque son hechos concretos del partido, no una tendencia
        // estadística) y punto único deja constancia en dataQuality.warning.
        cornersFor: 4,
        cornersAgainst: 5,
        shotsFor: 9,
        shotsAgainst: 10,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 4,
        possession: 49,
        yellowCards: 1,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h7",
        date: "2026-06-16",
        opponentId: "rival-anterior-11",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 4,
        goalsAgainst: 2,
        goalsForFirstHalf: 2,
        goalsForSecondHalf: 2,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 1,
        cornersFor: 8,
        cornersAgainst: 5,
        shotsFor: 18,
        shotsAgainst: 11,
        shotsOnTargetFor: 9,
        shotsOnTargetAgainst: 4,
        possession: 58,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h8",
        date: "2026-06-09",
        opponentId: "rival-anterior-12",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 1,
        goalsAgainst: 3,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 0,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 2,
        cornersFor: 3,
        cornersAgainst: 7,
        shotsFor: 7,
        shotsAgainst: 15,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 7,
        possession: 41,
        yellowCards: 3,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-local-ejemplo-h9",
        date: "2026-06-02",
        opponentId: "rival-anterior-13",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 0,
        cornersFor: 7,
        cornersAgainst: 3,
        shotsFor: 15,
        shotsAgainst: 8,
        shotsOnTargetFor: 7,
        shotsOnTargetAgainst: 2,
        possession: 57,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-local-ejemplo-h10",
        date: "2026-05-26",
        opponentId: "rival-anterior-14",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 0,
        cornersFor: 5,
        cornersAgainst: 5,
        shotsFor: 10,
        shotsAgainst: 10,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 4,
        possession: 50,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
    ],
    "equipo-visitante-ejemplo": [
      {
        matchId: "equipo-visitante-ejemplo-h1",
        date: "2026-07-29",
        opponentId: "rival-anterior-5",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 0,
        cornersFor: 4,
        cornersAgainst: 5,
        shotsFor: 10,
        shotsAgainst: 11,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 4,
        possession: 48,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 3,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h2",
        date: "2026-07-22",
        opponentId: "rival-anterior-6",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 0,
        cornersFor: 6,
        cornersAgainst: 2,
        shotsFor: 12,
        shotsAgainst: 6,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 1,
        possession: 55,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h3",
        date: "2026-07-15",
        opponentId: "rival-anterior-7",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 1,
        // Otro ejemplo de omisión legítima: se investigó, pero la fuente no
        // publicaba el desglose por tiempo ni las tarjetas del rival para
        // este partido — se omiten en vez de inventarlos.
        cornersFor: 3,
        cornersAgainst: 5,
        shotsFor: 7,
        shotsAgainst: 12,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 5,
        possession: 41,
        yellowCards: 2,
        redCards: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h4",
        date: "2026-07-08",
        opponentId: "rival-anterior-8",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 2,
        goalsAgainst: 2,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 1,
        cornersFor: 5,
        cornersAgainst: 5,
        shotsFor: 9,
        shotsAgainst: 9,
        shotsOnTargetFor: 4,
        shotsOnTargetAgainst: 4,
        possession: 50,
        yellowCards: 3,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 1,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h5",
        date: "2026-07-01",
        opponentId: "rival-anterior-9",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "W",
        goalsFor: 3,
        goalsAgainst: 1,
        goalsForFirstHalf: 2,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 7,
        cornersAgainst: 3,
        shotsFor: 14,
        shotsAgainst: 8,
        shotsOnTargetFor: 6,
        shotsOnTargetAgainst: 3,
        possession: 53,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h6",
        date: "2026-06-24",
        opponentId: "rival-anterior-10",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 2,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 0,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 1,
        cornersFor: 3,
        cornersAgainst: 6,
        shotsFor: 6,
        shotsAgainst: 13,
        shotsOnTargetFor: 1,
        shotsOnTargetAgainst: 6,
        possession: 39,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h7",
        date: "2026-06-17",
        opponentId: "rival-anterior-11",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 1,
        goalsAgainst: 1,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 0,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 5,
        cornersAgainst: 4,
        shotsFor: 9,
        shotsAgainst: 9,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 3,
        possession: 47,
        yellowCards: 3,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h8",
        date: "2026-06-10",
        opponentId: "rival-anterior-12",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "W",
        goalsFor: 2,
        goalsAgainst: 0,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 0,
        cornersFor: 6,
        cornersAgainst: 2,
        shotsFor: 11,
        shotsAgainst: 5,
        shotsOnTargetFor: 5,
        shotsOnTargetAgainst: 1,
        possession: 56,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
      {
        matchId: "equipo-visitante-ejemplo-h9",
        date: "2026-06-03",
        opponentId: "rival-anterior-13",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "local",
        result: "D",
        goalsFor: 2,
        goalsAgainst: 2,
        goalsForFirstHalf: 1,
        goalsForSecondHalf: 1,
        goalsAgainstFirstHalf: 1,
        goalsAgainstSecondHalf: 1,
        cornersFor: 4,
        cornersAgainst: 4,
        shotsFor: 8,
        shotsAgainst: 8,
        shotsOnTargetFor: 3,
        shotsOnTargetAgainst: 3,
        possession: 50,
        yellowCards: 2,
        redCards: 0,
        yellowCardsAgainst: 1,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "provided",
      },
      {
        matchId: "equipo-visitante-ejemplo-h10",
        date: "2026-05-27",
        opponentId: "rival-anterior-14",
        competitionId: "liga-ejemplo",
        competitionType: "league",
        venue: "visitante",
        result: "L",
        goalsFor: 0,
        goalsAgainst: 1,
        goalsForFirstHalf: 0,
        goalsForSecondHalf: 0,
        goalsAgainstFirstHalf: 0,
        goalsAgainstSecondHalf: 1,
        cornersFor: 3,
        cornersAgainst: 5,
        shotsFor: 6,
        shotsAgainst: 11,
        shotsOnTargetFor: 2,
        shotsOnTargetAgainst: 5,
        possession: 43,
        yellowCards: 1,
        redCards: 0,
        yellowCardsAgainst: 2,
        redCardsAgainst: 0,
        resultStatus: "verified",
        statsStatus: "estimated",
      },
    ],
  },
  dataQuality: {
    resultData: "verified",
    providedAdvancedStats: "provided",
    newAdvancedStats: "estimated",
    warning:
      "Los córners y remates de los partidos marcados como 'estimated' no se publican en la fuente y se estimaron a partir del marcador. El desglose de goles por tiempo y las tarjetas del rival se buscaron activamente en cada partido; se omiten solo en los dos registros donde la fuente consultada no los publicaba (nunca se estimaron, por ser hechos puntuales del partido).",
  },
  historyMeta: {
    matchesPerTeam: 10,
    newMatchesPerTeam: 10,
    sortOrder: "date_desc",
    verifiedFieldsForNewMatches: ["date", "opponentId", "competitionId", "venue", "result", "goalsFor", "goalsAgainst"],
    estimatedFieldsForNewMatches: [
      "cornersFor",
      "cornersAgainst",
      "shotsFor",
      "shotsAgainst",
      "shotsOnTargetFor",
      "shotsOnTargetAgainst",
      "possession",
      "yellowCards",
      "redCards",
    ],
  },
};

export const MATCH_PACKAGE_EXAMPLE_JSON = JSON.stringify({ version: 1, packages: [MATCH_PACKAGE_EXAMPLE] }, null, 2);

export const MATCH_PACKAGE_PROMPT = `Actúa como un investigador deportivo riguroso, no como un generador de datos plausibles. Necesito que investigues un partido de fútbol REAL (te diré cuál, o pregúntame si no te lo especifiqué) usando fuentes reales que hayas consultado de verdad, y me devuelvas exclusivamente un JSON con esta estructura exacta:

${MATCH_PACKAGE_EXAMPLE_JSON}

REGLA CERO, POR ENCIMA DE TODAS LAS DEMÁS: TERMINANTEMENTE PROHIBIDO INVENTAR DATOS.
Cada equipo, partido, fecha, resultado, rival, competición y fuente que pongas en el JSON tiene que corresponder a algo real que efectivamente encontraste al investigar — no a algo "razonable", "típico" o "que probablemente pasó". Si en algún momento no encontrás el dato real y no podés dejar de completar el campo (porque el esquema lo exige), tenés exactamente dos salidas válidas, nunca una tercera inventada:
   (a) Estimarlo de forma explícita y declarada como tal (ver regla 4), siempre partiendo de algo real (el marcador del partido, el promedio de la liga, el nivel de los equipos) — nunca un número que te "suene bien".
   (b) Preguntarme a mí en vez de completar el campo (ver regla 15).
Inventar resultados, marcadores, fechas, rivales, nombres de equipos, colores, estadios, o URLs de fuentes que no visitaste realmente es un fallo grave, no un detalle menor — arruina el propósito completo de este sistema, que es analizar datos reales, no ficción con apariencia de dato.

REGLAS QUE DEBES SEGUIR SIN EXCEPCIÓN:

1. Responde ÚNICAMENTE con el JSON. Nada de Markdown, nada de bloques de código (sin \`\`\`), nada de explicaciones antes o después, nada de comentarios dentro del JSON.
2. Respeta EXACTAMENTE la estructura del ejemplo: mismos nombres de campo, mismos tipos de dato, mismo anidamiento. No agregues campos que no estén en el ejemplo ni elimines campos obligatorios.
3. Usa ids únicos y en kebab-case (minúsculas, con guiones, sin espacios ni acentos) para "packages[].id", equipos, competiciones y "match.id". "histories" debe tener exactamente dos claves, una por cada id de "teams".
4. No inventes datos que se presenten como verificados. Resultados, marcadores, fechas, rivales, nombres, posiciones en tabla y URLs de fuentes deben salir de algo que realmente consultaste — jamás de una suposición. Todo lo que no puedas confirmar en una fuente real debe:
   - Marcarse con "statsStatus": "estimated" (o "resultStatus": "estimated" si el resultado mismo no está confirmado) en cada registro de historial afectado.
   - Explicarse en "dataQuality.warning", dejando claro qué parte es real y qué parte es estimación.
   Si terminás el JSON y no podrías señalar, para cada dato marcado como "verified", en qué fuente concreta de "sourceUrls" lo confirmaste, ese dato está mal marcado — bajalo a "estimated" o volvé a investigar.
5. Incluye EXACTAMENTE ${RECOMMENDED_HISTORY_PER_TEAM} partidos históricos reales por equipo en "histories" (nunca menos de ${MIN_HISTORY_PER_TEAM}, pero el estándar exigido es ${RECOMMENDED_HISTORY_PER_TEAM} para cada uno de los dos equipos, sin excepción). Cada registro con su "matchId" único. Si un equipo no tiene ${RECOMMENDED_HISTORY_PER_TEAM} partidos disputados todavía (equipo nuevo, temporada recién iniciada), incluye todos los que existan realmente, nunca menos de ${MIN_HISTORY_PER_TEAM}, y acláralo en "dataQuality.warning" — jamás inventes partidos para completar el número.
6. Ordena cada lista de historial de más reciente a más antiguo (por "date", descendente) — igual que en el ejemplo.
7. Incluye "sourceUrls" con las fuentes REALES que efectivamente consultaste para armar este JSON (mínimo una, URLs completas). No pongas una URL "típica" de un sitio de estadísticas si no la visitaste de verdad en esta investigación — cada fuente listada debe respaldar al menos un dato concreto que aparece en el paquete.
8. Usa fechas en formato YYYY-MM-DD, horas en HH:mm (24 horas) y "researchedAt" en formato ISO 8601 completo (YYYY-MM-DDTHH:mm:ss.000Z).
9. Usa colores hexadecimales de 6 dígitos (con #) para los campos de color.
10. "competitionType" debe ser uno de: league, cup, continental, friendly. "match.status" debe ser uno de: scheduled, live, finished, postponed.
11. "tier" y "totalTeams" de CADA competición en "competitions" deben ser números enteros mayores a 0, SIEMPRE — incluso para competiciones que no son una liga con tabla, como amistosos de pretemporada ("friendly"/"Club Friendlies"). En ese caso usa "tier": 1 y "totalTeams": 1 (nunca 0). Un valor de 0 en cualquiera de los dos hace que el JSON sea inválido.
12. Los campos "dataQuality.resultData", "dataQuality.providedAdvancedStats", "dataQuality.newAdvancedStats", y "resultStatus"/"statsStatus" de CADA registro de historial, SOLO pueden valer exactamente "verified", "provided" o "estimated" — nunca "none", "n/a", "unknown", "unavailable", "no_data", "not_available", "missing", ni ninguna otra palabra que se te ocurra para decir "no lo sé". Aunque te parezca más honesto inventar un cuarto estado, NO EXISTE: el validador solo acepta esos tres valores exactos y cualquier otro hace que el JSON entero sea rechazado. Si el dato no está disponible en ninguna fuente, usa "estimated" (ver regla siguiente) y explica la limitación en texto dentro de "dataQuality.warning".
13. Nunca completes un campo numérico que no encontraste con "0" repetido en todos los partidos como si fuera un marcador de "sin datos" — un 0 en "cornersFor", "shotsFor", "shotsOnTargetFor", "possession", etc. se interpreta como el valor real (cero córners, cero remates), y el sistema va a mostrarlo como un patrón real y falso (ej. "nunca superó los 0.5 córners"). Si de verdad no encontraste el dato exacto, estimalo de forma razonable a partir de: el promedio típico de esa liga/categoría, el marcador del partido, o el nivel de los equipos — y marca ese registro como "estimated", explicando en "dataQuality.warning" que son estimaciones y no cifras oficiales. Rellenar todo con 0 nunca es una estimación válida.
14. "match.time" y todas las horas que uses deben estar en la ZONA HORARIA LOCAL DEL ESTADIO donde se juega ("match.stadium"), no en tu propia zona horaria ni en la del usuario. Si detectas una diferencia horaria relevante entre fuentes, acláralo en texto dentro de "dataQuality.warning", pero nunca escribas la hora convertida a otro huso en el campo "time".
15. Antes de generar el JSON, si te falta información imprescindible (qué partido, en qué fecha, qué liga), PREGÚNTAME — no completes huecos con datos inventados.
16. Verifica tú mismo, antes de responder, que el JSON sea sintácticamente válido y que pueda ser procesado por un validador estricto (sin comas colgantes, sin comentarios, todas las comillas dobles, sin campos con valores fuera de los permitidos, y sin estadísticas numéricas en 0 repetidas en todos los partidos como relleno).
17. "yellowCards" y "redCards" (las del equipo investigado en ese registro, nunca las del rival) son OBLIGATORIAS en TODOS los registros, sin excepción — ya lo eran y lo siguen siendo. Además, "yellowCardsAgainst" y "redCardsAgainst" (las tarjetas del RIVAL en ese mismo partido histórico) DEJARON DE SER un extra opcional que agregás "si te sobra tiempo": son parte del chequeo estándar que tenés que hacer en la fuente para CADA partido del historial, igual que buscás el marcador o los córners. Solo se omiten cuando, después de revisar de verdad la fuente de ese partido puntual, confirmás que no publica las tarjetas del rival — nunca se estiman ni se inventan (a diferencia de córners/remates de la regla 13, una tarjeta es un hecho puntual del partido, no una tendencia que se pueda promediar; "estimar" una tarjeta es inventarla).
18. Lo mismo aplica al resultado al descanso: buscá activamente "goalsForFirstHalf"/"goalsForSecondHalf" (goles del equipo investigado en cada tiempo) y "goalsAgainstFirstHalf"/"goalsAgainstSecondHalf" (goles del rival al descanso) para CADA partido del historial — no es un dato decorativo que agregás si aparece a la primera, es parte de la investigación obligatoria de cada registro. Solo se omiten los cuatro juntos cuando confirmaste que la fuente de ese partido puntual no publica el resultado al descanso — nunca los inventes ni los estimes dividiendo el marcador final a la mitad "porque suena razonable". Si los incluís, "goalsForFirstHalf" + "goalsForSecondHalf" debe sumar exactamente "goalsFor" (mismo criterio para "goalsAgainst"), si no, el JSON se rechaza.

CHEQUEO FINAL OBLIGATORIO ANTES DE RESPONDER (hazlo en silencio, no lo escribas en la respuesta):
Repasa cada dato del JSON que estás por enviar y preguntate, uno por uno: "¿esto lo encontré de verdad en una fuente real, o lo estoy completando porque me falta el dato?". Si la respuesta es la segunda, ese campo tiene que estar marcado "estimated" (o preguntado antes de responder, nunca completado en silencio) — no hay una tercera opción de "lo dejo como si fuera real total nadie se va a dar cuenta". Este chequeo aplica también a "sourceUrls": no la incluyas si no la usaste de verdad.
Repasa además, partido por partido, si de verdad revisaste la fuente en busca del resultado al descanso y de las tarjetas del rival (regla 17 y 18) antes de omitirlas — omitir esos campos porque "no los busqué" no es una omisión legítima; solo lo es cuando SÍ los buscaste y confirmaste que la fuente no los publica para ese partido puntual.

Cuando tengas toda la información, responde solo con el JSON.`;
